#! /bin/bash
DGLBACKEND=pytorch python ../../dgl-ke-ogb-lsc/python/dglke/train.py --model_name DistMult \
--hidden_dim 512 --gamma 10 --lr 0.1 --regularization_coef 1e-9 \
--valid -adv --mix_cpu_gpu --num_proc 6 --num_thread 4 \
--batch_size 2000 \
--neg_sample_size 2000 \
--batch_size_eval 1 \
--print_on_screen \
--encoder_model_name shallow  \
--log_interval 1000 \
--is_eval 0 \
--save_entity_emb 1 \
--save_rel_emb 1 \
--save_mlp 1 \
--use_mmap 1 \
--eval_interval 25000 \
--max_step 10000000 \
--seed 13 \
--neg_sample_size_eval 19999 \
--gpu 0 1 \
--data_path /data/xu/data \
--dataset wikikg90m-v2 \
--save_path dglke_path/distmult_shallow